#include "gpu_preference.h"
#include "field_glsl.h"
#include "field_graph.h"
#include "raymarch_gl.h"

#include <glad/glad.h>
#include <GLFW/glfw3.h>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <memory>
#include <string>
#include <vector>

// dualc_glsl_parity -- the field->GLSL acceptance gate (roadmap docs/roadmap/12
// §B: "a preview==export parity test per analytic node"). For each node in the
// codegen's v1 slice it builds a single-node graph, compiles it to GLSL,
// evaluates sceneSDF(p) over an N^3 lattice on the GPU (rendered to an R32F
// FBO), and compares against the C++ field's valueAt(p) on the same points.
//
// "bit-faithful" is a tolerance, not literal: the CPU field is float64 and GPU
// sin/cos differ from libm, so closed-form analytic nodes get a tight epsilon
// while finite-difference nodes (normalize/twist/bend, which the GLSL emits with
// the SAME 1e-4 step) get a looser one. Non-zero exit if any node fails.
//
// Opt-in build (DUALC_BUILD_GLSL_PARITY); needs a GL context (a hidden window),
// so -- like the viewers -- it has no CTest and runs manually / where a GPU is
// available.

using dce::fieldgraph::GlslScene;
using dce::fieldgraph::GraphNode;

namespace {

constexpr int N = 16;          // samples per axis -> N^3 = 4096
constexpr int W = 64, H = 64;  // render target (W*H == N^3)

// What the GPU value is compared against.
//   Cpu         -- the exact C++ field. Every analytic node.
//   CpuSignOnly -- the exact C++ field, but only the SIGN must agree (points
//                  within one bake voxel of the surface are skipped). The right
//                  gate for a `mesh` node: the GPU samples a trilinear bake, so
//                  its magnitude legitimately differs, while a sign disagreement
//                  means dissolved or invented material.
//   BakedGrid   -- the scene's own baked grid, evaluated on the CPU. Gates the
//                  GL plumbing itself (texMin/texScale/texDim, the half-texel
//                  offset, GL_LINEAR, the R32F round-trip) rather than the bake.
enum class Ref { Cpu, CpuSignOnly, BakedGrid };

struct Case {
  std::string label;
  std::string expr;            // text shorthand
  dualc::BBox region;
  double absTol, relTol;
  Ref ref = Ref::Cpu;
};

// Demo meshes are gitignored and regenerated by dualc_gen_demo, and they are
// copied next to the built binaries -- so accept either cwd (the binary's own
// directory, or the repo root) and skip the case with a clear note if the mesh
// is absent rather than reporting a spurious FAIL.
std::string findDemoMesh(const std::string& name) {
  for (const std::string& cand : {name, "data/" + name}) {
    if (std::ifstream(cand, std::ios::binary).good()) return cand;
  }
  return {};
}

dualc::BBox box(double a, double b) {
  return dualc::BBox{{a, a, a}, {b, b, b}};
}

// Index -> sample point, identical to kValueFramework in field_glsl.cpp.
dualc::Vector3 samplePoint(int idx, const dualc::BBox& r) {
  const int ix = idx % N;
  const int iy = (idx / N) % N;
  const int iz = idx / (N * N);
  const dualc::Vector3 ext = r.extent();
  return dualc::Vector3{
      r.min.x + (ix + 0.5) / N * ext.x,
      r.min.y + (iy + 0.5) / N * ext.y,
      r.min.z + (iz + 0.5) / N * ext.z};
}

bool runCase(const Case& c, GLuint fbo) {
  dce::fieldgraph::FileMeshResolver resolver;
  GraphNode g;
  GlslScene scene;
  try {
    g = dce::fieldgraph::parseShorthand(c.expr);
    scene = dce::fieldgraph::compileToGlsl(g, resolver, c.region);
  } catch (const dce::fieldgraph::GraphError& e) {
    std::printf("  [%-16s] FAIL: %s\n", c.label.c_str(), e.what());
    return false;
  }

  const GLuint prog = dce::gl::linkProgram(
      dce::fieldgraph::vertexShaderSource(false),
      dce::fieldgraph::assembleValueShader(scene, false), c.label.c_str());
  if (!prog) { std::printf("  [%-16s] FAIL: shader\n", c.label.c_str()); return false; }

  GLuint vao = 0;
  glGenVertexArrays(1, &vao);
  glBindVertexArray(vao);
  glBindFramebuffer(GL_FRAMEBUFFER, fbo);
  glViewport(0, 0, W, H);
  glUseProgram(prog);
  const dualc::Vector3 ext = c.region.extent();
  dce::gl::setU3(prog, "uPMin", c.region.min);
  dce::gl::setU3(prog, "uPExt", ext);
  dce::gl::setU1i(prog, "uGrid", N);
  dce::gl::setU1i(prog, "uTexW", W);
  for (const auto& b : scene.bindings) {
    const GLint loc = glGetUniformLocation(prog, b.name.c_str());
    if (loc < 0) continue;
    if (b.glslType == "float") glUniform1f(loc, b.value[0]);
    else if (b.glslType == "vec3") glUniform3f(loc, b.value[0], b.value[1], b.value[2]);
    else if (b.glslType == "mat4") glUniformMatrix4fv(loc, 1, GL_TRUE, b.value.data());
  }
  std::vector<GLuint> meshTex;
  for (std::size_t m = 0; m < scene.meshes.size(); ++m) {
    const auto& mt = scene.meshes[m];
    meshTex.push_back(dce::gl::uploadGrid3D(prog, mt.samplerName, mt.region,
                                            mt.resolution, mt.values.data(),
                                            int(m)));
  }
  glClear(GL_COLOR_BUFFER_BIT);
  glDrawArrays(GL_TRIANGLES, 0, 3);
  glFinish();

  std::vector<float> gpu(static_cast<std::size_t>(W) * H, 0.0f);
  glPixelStorei(GL_PACK_ALIGNMENT, 1);
  glReadPixels(0, 0, W, H, GL_RED, GL_FLOAT, gpu.data());

  // Keep the FieldGraph alive: field() returns a reference INTO it, so binding to
  // the temporary build() result dangles (use-after-free). It happened to "work"
  // for the simple fields but crashes on displace's std::function bump.
  const dce::fieldgraph::FieldGraph fg =
      dce::fieldgraph::FieldGraph::build(g, resolver);
  const dualc::ImplicitField& field = fg.field();

  // BakedGrid: re-read the scene's own texture data on the CPU, so a mismatch
  // is GL plumbing rather than the bake.
  std::unique_ptr<dualc::GridField> baked;
  if (c.ref == Ref::BakedGrid && !scene.meshes.empty()) {
    const auto& mt = scene.meshes.front();
    baked = std::make_unique<dualc::GridField>(mt.region, mt.resolution,
                                               mt.values);
  }
  // One bake voxel: the band around the surface where a trilinear sample may
  // legitimately land on the far side of the zero crossing.
  double voxel = 0.0;
  for (const auto& mt : scene.meshes) {
    const dualc::Vector3 e = mt.region.extent();
    voxel = std::max(voxel, std::max({e.x, e.y, e.z}) /
                                std::max(mt.resolution.x - 1, 1));
  }

  double maxErr = 0.0;
  int worst = -1;
  int fails = 0;
  int compared = 0;   // sign cases: how many points actually got tested
  int inside = 0;     // ... and how many of those are inside the solid
  for (int idx = 0; idx < N * N * N; ++idx) {
    const dualc::Vector3 p = samplePoint(idx, c.region);
    const double cpu = baked ? baked->valueAt(p) : field.valueAt(p);
    if (c.ref == Ref::CpuSignOnly) {
      if (std::abs(cpu) < voxel) continue;   // within a voxel of the surface
      ++compared;
      if (cpu < 0.0) ++inside;
      if ((double(gpu[idx]) < 0.0) == (cpu < 0.0)) continue;
      if (std::abs(cpu) > maxErr) { maxErr = std::abs(cpu); worst = idx; }
      ++fails;
      continue;
    }
    const double err = std::abs(double(gpu[idx]) - cpu);
    if (err > maxErr) { maxErr = err; worst = idx; }
    if (err > c.absTol + c.relTol * std::abs(cpu)) ++fails;
  }
  glDeleteProgram(prog);
  glDeleteVertexArrays(1, &vao);
  if (!meshTex.empty())
    glDeleteTextures(GLsizei(meshTex.size()), meshTex.data());

  // A sign case that compared nothing, or that sampled no interior at all, is
  // vacuous -- it would "pass" against arbitrarily broken code. Fail it, and say
  // so, rather than reporting a green tick for an empty comparison.
  const bool vacuous = c.ref == Ref::CpuSignOnly && (compared == 0 || inside == 0);
  const bool ok = fails == 0 && !vacuous;
  if (c.ref == Ref::CpuSignOnly) {
    std::printf("  [%-16s] %s  sign wrong %d/%d  (%d inside)%s\n",
                c.label.c_str(), ok ? "ok  " : "FAIL", fails, compared, inside,
                vacuous ? "  <- VACUOUS: nothing compared" : "");
  } else {
    std::printf("  [%-16s] %s  maxErr %.2e  (%d/%d over tol)\n",
                c.label.c_str(), ok ? "ok  " : "FAIL", maxErr, fails,
                N * N * N);
  }
  if (!ok && worst >= 0) {
    const dualc::Vector3 p = samplePoint(worst, c.region);
    std::printf("                     worst @ (%.3f,%.3f,%.3f): gpu %.5f cpu %.5f\n",
                p.x, p.y, p.z, double(gpu[worst]), field.valueAt(p));
  }
  return ok;
}

}  // namespace

int main() {
  // Some GL drivers tear the process down in glfwTerminate() without flushing C
  // stdio, which would swallow buffered results -- make stdout unbuffered.
  std::setvbuf(stdout, nullptr, _IONBF, 0);
  GLFWwindow* win = dce::gl::initWindow("dualc_glsl_parity", W, H, false);
  if (!win) return 1;

  // R32F render target.
  GLuint fbo = 0, tex = 0;
  glGenFramebuffers(1, &fbo);
  glGenTextures(1, &tex);
  glBindTexture(GL_TEXTURE_2D, tex);
  glTexImage2D(GL_TEXTURE_2D, 0, GL_R32F, W, H, 0, GL_RED, GL_FLOAT, nullptr);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
  glBindFramebuffer(GL_FRAMEBUFFER, fbo);
  glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, tex, 0);
  if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE) {
    std::printf("FAIL: R32F framebuffer incomplete (no float-render support)\n");
    glfwTerminate();
    return 1;
  }

  const double A = 2e-3, R = 2e-3;     // closed-form analytic tier
  const double FA = 3e-2, FR = 3e-2;   // finite-difference tier
  const std::vector<Case> cases = {
      // primitives (one per tier: A sphere/box/roundbox/torus, B cone, C triangle)
      {"sphere", "sphere(radius=1)", box(-2, 2), A, R},
      {"box", "box(min=[-1,-1,-1],max=[1,1,1])", box(-2, 2), A, R},
      {"roundbox", "roundbox(min=[-1,-1,-1],max=[1,1,1],radius=0.3)", box(-2, 2), A, R},
      {"torus", "torus(major=1,minor=0.3)", box(-2, 2), A, R},
      {"cone", "cone()", box(-2, 2), A, R},
      {"triangle", "triangle()", box(-1, 2), A, R},
      // TPMS (all six)
      {"gyroid", "gyroid(wavelength=1)", box(-1, 1), A, R},
      {"schwarz-p", "schwarz_p(wavelength=1)", box(-1, 1), A, R},
      {"diamond", "diamond(wavelength=1)", box(-1, 1), A, R},
      {"fischer-koch", "fischer_koch(wavelength=1)", box(-1, 1), A, R},
      {"lidinoid", "lidinoid(wavelength=1)", box(-1, 1), A, R},
      {"neovius", "neovius(wavelength=1)", box(-1, 1), A, R},
      // strut lattices (exact SDFs -> tight tier). One period across the box so
      // the single round-fold and several tiles are exercised.
      {"sc", "sc(wavelength=1,radius=0.1)", box(-1, 1), A, R},
      {"bcc", "bcc(wavelength=1,radius=0.1)", box(-1, 1), A, R},
      {"fcc", "fcc(wavelength=1,radius=0.1)", box(-1, 1), A, R},
      {"octet", "octet(wavelength=1,radius=0.1)", box(-1, 1), A, R},
      // tapered struts: fat (nodeRadius) at the nodes, thin (radius) mid-span --
      // a min of exact round cones, so it stays at the tight tier.
      {"bcc-taper", "bcc(wavelength=1,radius=0.06,nodeRadius=0.14)", box(-1, 1), A, R},
      // booleans
      {"union", "union(sphere(center=[-0.5,0,0]),sphere(center=[0.5,0,0]))", box(-2, 2), A, R},
      {"intersection", "intersection(sphere(center=[-0.4,0,0]),sphere(center=[0.4,0,0]))", box(-2, 2), A, R},
      {"difference", "difference(sphere(radius=1),sphere(center=[0.5,0,0],radius=0.7))", box(-2, 2), A, R},
      {"xor", "xor(sphere(center=[-0.4,0,0]),sphere(center=[0.4,0,0]))", box(-2, 2), A, R},
      {"smooth-union", "smooth_union(sphere(center=[-0.5,0,0]),sphere(center=[0.5,0,0]),k=0.3)", box(-2, 2), A, R},
      {"smooth-inter", "smooth_intersection(sphere(center=[-0.4,0,0]),sphere(center=[0.4,0,0]),k=0.3)", box(-2, 2), A, R},
      {"smooth-diff", "smooth_difference(sphere(radius=1),sphere(center=[0.5,0,0],radius=0.7),k=0.3)", box(-2, 2), A, R},
      // decorators
      {"offset", "offset(sphere(radius=1),r=0.2)", box(-2, 2), A, R},
      {"onion", "onion(sphere(radius=1),thickness=0.1)", box(-2, 2), A, R},
      // graded-onion over an analytic base+control isolates the remap math at
      // the tight tier (control = sphere(radius=0) = distance from the origin).
      {"graded-onion",
       "graded-onion(sphere(center=[0,2,0],radius=1),sphere(radius=0),"
       "t1=0.05,t2=0.25,d0=0.5,d1=1.5)",
       box(-2, 2), A, R},
      // graded-offset: same remap math, inflates a metric base (sphere) so the
      // SDF stays exact -> tight tier. control = distance from the origin.
      {"graded-offset",
       "graded-offset(sphere(center=[0,2,0],radius=1),sphere(radius=0),"
       "t1=0.05,t2=0.25,d0=0.5,d1=1.5)",
       box(-2, 2), A, R},
      // mix morph: value = lerp(A,B,w). The lerp/clamp is the identical formula
      // in C++ and GLSL, so with analytic children it parities at the tight tier
      // (control = sphere(radius=0) = distance from the origin).
      {"mix",
       "mix(sphere(center=[-0.6,0,0],radius=0.8),"
       "sphere(center=[0.6,0,0],radius=0.8),sphere(radius=0),lo=0.3,hi=1.2)",
       box(-2, 2), A, R},
      {"scale", "scale(sphere(radius=1),s=1.5)", box(-3, 3), A, R},
      {"elongate", "elongate(sphere(radius=0.5),h=[0.5,0,0])", box(-2, 2), A, R},
      {"translate", "translate(sphere(radius=1),by=[0.5,0.2,0])", box(-2, 2), A, R},
      {"rotate", "rotate(box(min=[-1,-0.3,-0.3],max=[1,0.3,0.3]),axis=[0,0,1],degrees=30)", box(-2, 2), A, R},
      // finite-difference tier (looser tol)
      {"normalize", "normalize(gyroid(wavelength=1))", box(-1, 1), FA, FR},
      // realistic graded shell on a normalized gyroid (inherits normalize's FD tier).
      {"graded-onion-tpms",
       "graded-onion(normalize(gyroid(wavelength=1)),sphere(radius=0),"
       "t1=0.05,t2=0.2,d0=0.2,d1=1.2)",
       box(-1, 1), FA, FR},
      {"twist", "twist(box(min=[-1,-0.3,-0.3],max=[1,0.3,0.3]),radiansPerUnit=0.5,axis=x)", box(-2, 2), FA, FR},
      {"bend", "bend(box(min=[-1,-0.3,-0.3],max=[1,0.3,0.3]),curvature=0.4,axis=x)", box(-2, 2), FA, FR},
      // DAG dedup: a duplicated subtree collapses to one fN -- sceneSDF must be
      // unchanged (union(g,g) == g). Renders identically to a single gyroid.
      {"dedup", "union(gyroid(wavelength=1),gyroid(wavelength=1))", box(-1, 1), A, R},
      // domain ops (round/mirror/repeat/repeat-limited are exact arithmetic ->
      // tight tier; displace uses GPU trig -> same tier as TPMS, may need FD if it
      // trips on a driver).
      {"round", "round(sphere(radius=1),r=0.2)", box(-2, 2), A, R},
      {"mirror", "mirror(sphere(center=[0.6,0,0],radius=0.5),normal=[1,0,0])", box(-2, 2), A, R},
      {"repeat", "repeat(sphere(radius=0.3),period=[1,1,1])", box(-1, 1), A, R},
      {"repeat-limited", "repeat-limited(sphere(radius=0.3),period=[1,1,1],count=[2,2,2])", box(-1, 2), A, R},
      {"displace-sine", "displace(sphere(radius=1),fn=sine,amplitude=0.2,frequency=4)", box(-2, 2), A, R},
      {"displace-gyroid", "displace(sphere(radius=1),fn=gyroid,amplitude=0.2,frequency=4)", box(-2, 2), A, R},
      {"displace-bumps", "displace(sphere(radius=1),fn=bumps,amplitude=0.2,frequency=4)", box(-2, 2), A, R},
      // primitive long tail (registry defaults; closed-form -> tight tier, the
      // trig ones like cone within the same tolerance). Infinite/open shapes are
      // clipped by the sample box.
      // Positional: `plane` has no grouped keys. The earlier spelling
      // `plane(normal=[0,1,0],offset=0)` was silently ignored and only "passed"
      // because its value equalled the registry default (roadmap 17/10).
      {"plane", "plane(0,1,0,0)", box(-2, 2), A, R},
      {"capsule", "capsule()", box(-2, 2), A, R},
      {"cappedcylinder", "cappedcylinder()", box(-2, 2), A, R},
      {"ellipsoid", "ellipsoid()", box(-2, 2), A, R},
      {"boxframe", "boxframe()", box(-2, 2), A, R},
      {"cappedcone", "cappedcone()", box(-2, 2), A, R},
      {"roundcone", "roundcone()", box(-2, 2), A, R},
      {"infinitecylinder", "infinitecylinder()", box(-2, 2), A, R},
      {"hexprism", "hexprism()", box(-2, 2), A, R},
      {"triprism", "triprism()", box(-2, 2), A, R},
      {"octahedron", "octahedron()", box(-2, 2), A, R},
      {"pyramid", "pyramid()", box(-2, 2), A, R},
      {"solidangle", "solidangle()", box(-2, 2), A, R},
      {"cappedtorus", "cappedtorus()", box(-2, 2), A, R},
      {"link", "link()", box(-2, 2), A, R},
      {"cutsphere", "cutsphere()", box(-2, 2), A, R},
      {"cuthollowsphere", "cuthollowsphere()", box(-2, 2), A, R},
      {"deathstar", "deathstar()", box(-2, 2), A, R},
      {"vesica", "vesica()", box(-2, 2), A, R},
      {"rhombus", "rhombus()", box(-2, 2), A, R},
      {"verticalcapsule", "verticalcapsule()", box(-2, 2), A, R},
      {"roundedcylinder", "roundedcylinder()", box(-2, 2), A, R},
      {"quad", "quad()", box(-1, 2), A, R},
      {"infinitecone", "infinitecone()", box(-2, 2), A, R},
  };

  // ---- baked sources (mesh / winding) --------------------------------------
  // The bake is the only APPROXIMATE node in the codegen and, for a long time,
  // the only ungated one -- which is how a far-field sign bug (interior material
  // dissolving whenever the bake region was not padded around the mesh) and a
  // silently-ignored --grid-res both shipped. cube.obj is the demo cube, spanning
  // [-0.5,0.5]^3 -- the regions below are chosen against that extent.
  std::vector<Case> runList = cases;
  const std::string cubePath = findDemoMesh("cube.obj");
  if (cubePath.empty()) {
    std::printf("  [mesh cases      ] SKIP: cube.obj found neither next to the "
                "binary nor under data/ -- run from the repo root, or from a "
                "build dir where a mesh-consuming example has been built\n");
  } else {
    const std::string meshExpr = "mesh(path=\"" + cubePath + "\")";
    // (a) SIGN parity over a box STRICTLY INSIDE the cube. The bake region is
    //     the compile bounds, so this is exactly the sub-box case the preview
    //     hits on intersection(mesh, smaller_shape) or a --bounds zoom. Every
    //     sample must read inside; the pre-fix bake read them all as outside.
    runList.push_back({"mesh-inside", meshExpr, box(-0.4, 0.4), A, R,
                       Ref::CpuSignOnly});
    // (b) SIGN parity over a box the cube only partly fills: the -x/-y/-z faces
    //     sit 0.3 inside the solid -- well beyond the band, so those face voxels
    //     are exactly the ones the old face-seeded flood mislabelled -- while
    //     +x/+y/+z are genuinely outside.
    runList.push_back({"mesh-straddle", meshExpr,
                       dualc::BBox{{-0.2, -0.2, -0.2}, {1.5, 1.5, 1.5}}, A, R,
                       Ref::CpuSignOnly});
    // (c) GPU vs CPU on the SAME baked grid: gates the upload plumbing
    //     (texMin/texScale/texDim, the half-texel offset, GL_LINEAR, the R32F
    //     round-trip) rather than the bake. Tolerance is filter precision.
    runList.push_back({"mesh-texture", meshExpr, box(-2, 2), 2e-3, 2e-3,
                       Ref::BakedGrid});
  }
  if (!cubePath.empty()) {
    // winding bakes 0.5 - windingNumber over the full lattice (no band): same
    // upload path, different producer. Reuse the cube with a region that
    // STRADDLES its surface -- a box wholly inside (or wholly outside) any mesh
    // samples a constant field, where a wrong texScale/texMin/texDim still reads
    // the right constant back and the case would gate nothing.
    runList.push_back({"winding-texture", "winding(path=\"" + cubePath + "\")",
                       box(-1, 1), 2e-3, 2e-3, Ref::BakedGrid});
  }

  std::printf("dualc_glsl_parity: %zu cases, %d^3 samples each\n", runList.size(), N);
  int failed = 0;
  for (const Case& c : runList)
    if (!runCase(c, fbo)) ++failed;

  std::printf("\n%s: %d/%zu passed\n", failed ? "FAILURES" : "all passed",
              int(runList.size()) - failed, runList.size());
  glDeleteFramebuffers(1, &fbo);
  glDeleteTextures(1, &tex);
  glfwDestroyWindow(win);
  glfwTerminate();
  return failed ? 1 : 0;
}
